# Generated by Django 2.2.10 on 2020-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_field', 'Text field'), ('checkbox', 'Single choice'), ('radio_button', 'Multiple choice')], max_length=100),
        ),
    ]
