# Generated by Django 2.2.10 on 2020-07-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200730_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_variants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Quiz'),
        ),
    ]
